name: Sandkassinn
main: is.gussi.bukkit.plugin.sandkassin.Sandkassin
version: 0.1
website: http://github.com/gussi/Sandkassinn
author: Gussi
description: Sandkassinn - Various functionality for Sandkassinn (gussi.is
